apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipiece-backend-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kohtaewoo/ipiece-manifests-test.git'
    targetRevision: main
    path: backend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ipiece-backend-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
